doctrine:
    dbal:
        types:
            service_id: App\SpaServices\Infrastructure\Persistence\Doctrine\ServiceIdType
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Service:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/SpaServices/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Entity\Domain'
                alias: Service
    
    
